# Generated by Django 3.2.9 on 2021-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='parts',
            field=models.IntegerField(default=0),
        ),
    ]
