# Generated by Django 3.2.9 on 2021-12-09 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='parts',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
