# Generated by Django 3.2.9 on 2021-12-02 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
