# Generated by Django 3.2.9 on 2021-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20211202_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
