# Generated by Django 3.2.9 on 2021-12-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_income_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcome',
            old_name='book_income',
            new_name='book',
        ),
    ]
