# Generated by Django 3.2.9 on 2021-12-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_rename_book_income_outcome_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='part',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outcome',
            name='pub_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
