# Generated by Django 3.2.9 on 2021-12-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_auto_20211205_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
