# Generated by Django 3.2.9 on 2021-12-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='fund_count',
            new_name='income_count',
        ),
        migrations.AddField(
            model_name='fund',
            name='outcome_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='pupils',
            field=models.IntegerField(default=0),
        ),
    ]
