# Generated by Django 3.2.9 on 2021-12-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_rename_overall_count_fund_exchange_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='is_outcome',
            field=models.BooleanField(default=False),
        ),
    ]
