# Generated by Django 3.2.9 on 2021-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_exchange_is_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='income_count_ex',
            field=models.IntegerField(default=0),
        ),
    ]
