# Generated by Django 3.2.9 on 2021-12-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_parts'),
        ('funds', '0013_auto_20211205_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='is_outcome',
        ),
        migrations.AddField(
            model_name='exchange',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.document'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AlterField(
            model_name='income',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AlterField(
            model_name='income',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.document'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.document'),
        ),
    ]
