# Generated by Django 3.2.9 on 2021-12-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_parts'),
        ('funds', '0015_alter_outcome_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange', to='funds.income'),
        ),
        migrations.AlterField(
            model_name='income',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='books.book'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to='funds.income'),
        ),
    ]
