# Generated by Django 3.2.9 on 2021-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0017_alter_exchange_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='is_income',
            field=models.BooleanField(default=True),
        ),
    ]
