# Generated by Django 3.2.9 on 2021-12-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0018_exchange_is_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='income_count',
            new_name='fund_count',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='income_count_ex',
            new_name='overall_count',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='outcome_count',
        ),
    ]
