# Generated by Django 3.2.9 on 2021-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0019_auto_20211209_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='records_count',
            field=models.IntegerField(default=0),
        ),
    ]
