# Generated by Django 3.2.9 on 2021-12-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_parts'),
        ('funds', '0020_fund_records_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('count', models.IntegerField(default=0)),
                ('part', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('pub_year', models.IntegerField(default=2021)),
                ('comment', models.CharField(blank=True, max_length=80, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('is_income', models.BooleanField(default=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
            ],
        ),
        migrations.RemoveField(
            model_name='income',
            name='book',
        ),
        migrations.RemoveField(
            model_name='income',
            name='document',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='book',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_order',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
        migrations.AddField(
            model_name='item',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.document'),
        ),
    ]
