# Generated by Django 3.2.9 on 2021-12-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0021_auto_20211211_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_income',
        ),
    ]
